# vim:ft=ansible:
---
- hosts: 192.168.0.30
  user: joseph
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
          - mysql_password: !vault |
                      $ANSIBLE_VAULT;1.1;AES256
                      36383838396135643530633438346132653563643565633961653531353230323230626261363066
                      6565353830623134646562313336343339393139366133640a653432363064346232303762643432
                      35313439323565353332373363313238343031643261313930646639326365613337656339386333
                      6436376337343466310a643631336638376366303262343238653130663137363965663739613663
                      3737
  
                      
  tasks:
          # --Install HTTPD, MariaDB and PHP--
          - name: Install HTTPD, MariaDB and PHP
            yum: 
                    name: ['httpd', '@mariadb', '@mariadb-server', 'php', 'php-mysql', 'firewalld', 'expect']
                    state: latest
            notify: 
                    - Enable & Restart HTTPD
                    - Enable & Restart mariadb
                    - Enable & Restart firewalld


          - name: Flush Services
            meta: flush_handlers


          - name: Configure MariaDB
            expect:
                    command: mysql_secure_installation
                    responses:
                            'Enter current password for root': ''
                            'Set root password': 'Y'
                            'New password': '{{ mysql_password }}'
                            'Re-enter new password': '{{ mysql_password }}'
                            'Remove anonymous users': 'Y'
                            'Disallow root login remotely': 'n'
                            'Remove test database and access to it': 'n'
                            'Reload privilege tables now': 'Y'
            notify:
                    - Enable & Restart mariadb


            # ---This will create info.php file to test PHP---          
          - name: Create test file to test PHP
            lineinfile: 
                    path: "/var/www/html/info.php" 
                    line: "<?php phpinfo(); ?>" 
                    mode: "0766" 
                    create: yes 
                    state: present

                            
          - name: Edit firewall rules
            firewalld: service={{ item }} permanent=yes state=enabled
            with_items:
                    - http
                    - https
                    - mysql
            notify:
                    - Enable & Restart firewalld


  handlers:
          - name: Enable & Restart HTTPD
            service: name=httpd state=restarted enabled=yes

          - name: Enable & Restart mariadb
            service: name=mariadb state=restarted enabled=yes
          
          - name: Enable & Restart firewalld
            service: name=firewalld state=restarted enabled=yes
